getwd()
setwd("/Users/qinliuvt.edu/Downloads")
data<-read.table('household_power_consumption.txt',sep=';', header = TRUE)
object.size(data)
head(data)
str(data)
datadf<-data[data$Date=='1/2/2007'|data$Date=='2/2/2007',]
datadf$datetime<-strptime(paste(datadf$Date, datadf$Time), format="%d/%m/%Y %H:%M:%S")
names(datadf)

datadf$Global_active_power<-as.numeric(datadf$Global_active_power)
datadf$Sub_metering_1<-as.numeric(datadf$Sub_metering_1)
datadf$Sub_metering_2<-as.numeric(datadf$Sub_metering_2)

png('plot3.png', width = 480, height = 480)
plot(datadf$datetime, datadf$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(datadf$datetime, datadf$Sub_metering_2, type="l", col="red")
lines(datadf$datetime, datadf$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
